name: flower_site
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  simple_icons: ^10.1.3
  firebase_core: ^3.8.0
  firebase_data_connect: ^0.1.2+3
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/image_middle.png
    - assets/images/image_logo.png
  #   - images/a_dot_ham.jpeg




