// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8h7rztaKQ5cDNGGzuIgZ6NE0XIflw3I',
    appId: '1:704911687004:web:361e65b20e4c90b7845599',
    messagingSenderId: '704911687004',
    projectId: 'app-exam-5cc5d',
    authDomain: 'app-exam-5cc5d.firebaseapp.com',
    databaseURL: 'https://app-exam-5cc5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-exam-5cc5d.appspot.com',
    measurementId: 'G-X644GY17QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAIVpZYPlbjWrSDSQPhAljTXmbyP3atIk',
    appId: '1:704911687004:android:54f4bc4c82c8d3d5845599',
    messagingSenderId: '704911687004',
    projectId: 'app-exam-5cc5d',
    databaseURL: 'https://app-exam-5cc5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-exam-5cc5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVcnHWLhGx5S4rQZLbm5ScL-h9Ckl5UQ',
    appId: '1:704911687004:ios:1f7f84e910218310845599',
    messagingSenderId: '704911687004',
    projectId: 'app-exam-5cc5d',
    databaseURL: 'https://app-exam-5cc5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-exam-5cc5d.appspot.com',
    iosBundleId: 'com.example.flowerSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVcnHWLhGx5S4rQZLbm5ScL-h9Ckl5UQ',
    appId: '1:704911687004:ios:1f7f84e910218310845599',
    messagingSenderId: '704911687004',
    projectId: 'app-exam-5cc5d',
    databaseURL: 'https://app-exam-5cc5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-exam-5cc5d.appspot.com',
    iosBundleId: 'com.example.flowerSite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW8h7rztaKQ5cDNGGzuIgZ6NE0XIflw3I',
    appId: '1:704911687004:web:48e6da23b1850cc2845599',
    messagingSenderId: '704911687004',
    projectId: 'app-exam-5cc5d',
    authDomain: 'app-exam-5cc5d.firebaseapp.com',
    databaseURL: 'https://app-exam-5cc5d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-exam-5cc5d.appspot.com',
    measurementId: 'G-F050YHM8Y5',
  );

}